server:
  port: 8760

spring:
  cloud:
    gateway:
      routes:
      - id: productModule
        uri: http://localhost:8081/
        predicates:
        - Path=/product/**
      - id: orderModule
        uri: http://localhost:8082/
        predicates:
        - Path=/order/**