eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    healthcheck:
      enabled: true
  serviceUrl:
    defaultZone: http://backend-eureka-server:8761/eureka
server:
  port: 8761
spring:
  application:
    name: backend-eureka-server